import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    // 1. Parse JSON body
    let body: any;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ error: "Invalid JSON request body." }, { status: 400 });
    }

    const { name, email, subject, message, website, pageUrl } = body;

    // 2. Honeypot check
    if (website && typeof website === "string" && website.trim() !== "") {
      console.warn("Spam submission blocked via honeypot field (Next.js Route).");
      return NextResponse.json({
        success: true,
        message: "Thank you! Your message has been sent successfully.",
      }, { status: 200 });
    }

    // 3. Validation
    if (!name || typeof name !== "string" || name.trim() === "") {
      return NextResponse.json({ error: "Name is required." }, { status: 400 });
    }
    if (name.length > 100) {
      return NextResponse.json({ error: "Name must be 100 characters or less." }, { status: 400 });
    }

    if (!email || typeof email !== "string" || email.trim() === "") {
      return NextResponse.json({ error: "Email is required." }, { status: 400 });
    }
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email.trim())) {
      return NextResponse.json({ error: "Please provide a valid email address." }, { status: 400 });
    }

    if (!subject || typeof subject !== "string" || subject.trim() === "") {
      return NextResponse.json({ error: "Subject is required." }, { status: 400 });
    }
    if (subject.length > 200) {
      return NextResponse.json({ error: "Subject must be 200 characters or less." }, { status: 400 });
    }

    if (!message || typeof message !== "string" || message.trim() === "") {
      return NextResponse.json({ error: "Message is required." }, { status: 400 });
    }
    if (message.length > 5000) {
      return NextResponse.json({ error: "Message must be 5000 characters or less." }, { status: 400 });
    }

    // 4. Check API configuration
    const resendApiKey = process.env.RESEND_API_KEY?.trim();
    if (!resendApiKey) {
      console.error("Configuration Error: RESEND_API_KEY is not defined in process.env.");
      return NextResponse.json({ error: "Email sending configuration is missing on the server." }, { status: 500 });
    }

    const contactToEmail = process.env.CONTACT_TO_EMAIL?.trim() || "support@rentx.us";

    // 5. Construct Email Contents
    const submittedAt = new Date().toISOString();
    const sourceUrl = pageUrl && typeof pageUrl === "string" ? pageUrl : request.headers.get("referer") || "Unknown Page";

    const emailSubject = `New RentX Contact Form Submission: ${subject.trim()}`;

    const textContent = `
New RentX Contact Form Submission

Date/Time: ${submittedAt}
Page URL: ${sourceUrl}

----------------------------------------
Name: ${name.trim()}
Email: ${email.trim()}
Subject: ${subject.trim()}
Message:
${message.trim()}
----------------------------------------
    `.trim();

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 8px; }
    h2 { color: #0E2A23; border-bottom: 2px solid #C78B5E; padding-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    td { padding: 8px; vertical-align: top; }
    td.label { font-weight: bold; width: 120px; color: #555; }
    .message-box { background-color: #f9f9f9; border-left: 4px solid #C78B5E; padding: 15px; white-space: pre-wrap; font-size: 14px; }
    .footer { font-size: 11px; color: #888; margin-top: 20px; border-top: 1px solid #eee; padding-top: 10px; }
  </style>
</head>
<body>
  <div class="container">
    <h2>New RentX Contact Form Submission</h2>
    <table>
      <tr>
        <td class="label">Date/Time:</td>
        <td>${submittedAt}</td>
      </tr>
      <tr>
        <td class="label">Page URL:</td>
        <td><a href="${sourceUrl}">${sourceUrl}</a></td>
      </tr>
      <tr>
        <td class="label">Name:</td>
        <td>${name.trim()}</td>
      </tr>
      <tr>
        <td class="label">Email:</td>
        <td><a href="mailto:${email.trim()}">${email.trim()}</a></td>
      </tr>
      <tr>
        <td class="label">Subject:</td>
        <td>${subject.trim()}</td>
      </tr>
    </table>
    
    <p><strong>Message:</strong></p>
    <div class="message-box">${message.trim().replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
    
    <div class="footer">
      This email was automatically generated by the RentX Contact Form Handler on Cloudflare Pages.
    </div>
  </div>
</body>
</html>
    `;

    // 6. Send via Resend API
    const resendResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${resendApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "RentX Contact <support@rentx.us>",
        to: [contactToEmail],
        reply_to: email.trim(),
        subject: emailSubject,
        text: textContent,
        html: htmlContent,
      }),
    });

    if (!resendResponse.ok) {
      const resendErrorText = await resendResponse.text();
      console.error("Resend API Error (Next.js Route):", resendErrorText);
      return NextResponse.json({ error: `Failed to send email: ${resendErrorText}` }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      message: "Thank you! Your message has been sent successfully.",
    }, { status: 200 });
  } catch (error: any) {
    console.error("Contact Form Next.js Route Error:", error);
    return NextResponse.json({ error: "An unexpected error occurred while processing your request." }, { status: 500 });
  }
}
