import { NextResponse } from "next/server";

export async function POST(request: Request) {
  const responseHeaders = new Headers({
    "Content-Type": "application/json",
  });

  try {
    // 1. Read JSON body: name, email, message
    let body: any;
    try {
      body = await request.json();
    } catch (err) {
      console.error("[Route Handler] Error parsing JSON body:", err);
      return NextResponse.json({ success: false, error: "Invalid JSON body." }, { status: 400 });
    }

    const { name, email, message } = body;

    // 2. Validation
    if (!name || typeof name !== "string" || name.trim() === "") {
      return NextResponse.json({ success: false, error: "Name is required." }, { status: 400 });
    }
    if (name.length > 100) {
      return NextResponse.json({ success: false, error: "Name must be 100 characters or less." }, { status: 400 });
    }

    if (!email || typeof email !== "string" || email.trim() === "") {
      return NextResponse.json({ success: false, error: "Email is required." }, { status: 400 });
    }
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email.trim())) {
      return NextResponse.json({ success: false, error: "Please provide a valid email address." }, { status: 400 });
    }

    if (!message || typeof message !== "string" || message.trim() === "") {
      return NextResponse.json({ success: false, error: "Message is required." }, { status: 400 });
    }
    if (message.length > 3000) {
      return NextResponse.json({ success: false, error: "Message must be 3000 characters or less." }, { status: 400 });
    }

    // 3. Use env variables
    const resendApiKey = process.env.RESEND_API_KEY?.trim() || (globalThis as any).RESEND_API_KEY?.trim();
    const contactToEmail = process.env.CONTACT_TO_EMAIL?.trim() || (globalThis as any).CONTACT_TO_EMAIL?.trim();

    if (!resendApiKey) {
      console.error("[Route Handler] Missing RESEND_API_KEY environment variable.");
      return NextResponse.json({ success: false, error: "Email sending configuration is missing on the server." }, { status: 500 });
    }

    if (!contactToEmail) {
      console.error("[Route Handler] Missing CONTACT_TO_EMAIL environment variable.");
      return NextResponse.json({ success: false, error: "Destination email configuration is missing on the server." }, { status: 500 });
    }

    // 4. Construct email body (include Name, Email, Message, Date, Page URL)
    const date = new Date().toISOString();
    const pageUrl = request.headers.get("referer") || "Unknown Page";

    const textContent = `
New RentX Contact Form Submission

Date: ${date}
Page URL: ${pageUrl}

----------------------------------------
Name: ${name.trim()}
Email: ${email.trim()}
Message:
${message.trim()}
----------------------------------------
    `.trim();

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 8px; }
    h2 { color: #0E2A23; border-bottom: 2px solid #C78B5E; padding-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    td { padding: 8px; vertical-align: top; }
    td.label { font-weight: bold; width: 120px; color: #555; }
    .message-box { background-color: #f9f9f9; border-left: 4px solid #C78B5E; padding: 15px; white-space: pre-wrap; font-size: 14px; }
    .footer { font-size: 11px; color: #888; margin-top: 20px; border-top: 1px solid #eee; padding-top: 10px; }
  </style>
</head>
<body>
  <div class="container">
    <h2>New RentX Contact Form Submission</h2>
    <table>
      <tr>
        <td class="label">Date:</td>
        <td>${date}</td>
      </tr>
      <tr>
        <td class="label">Page URL:</td>
        <td><a href="${pageUrl}">${pageUrl}</a></td>
      </tr>
      <tr>
        <td class="label">Name:</td>
        <td>${name.trim()}</td>
      </tr>
      <tr>
        <td class="label">Email:</td>
        <td><a href="mailto:${email.trim()}">${email.trim()}</a></td>
      </tr>
    </table>
    
    <p><strong>Message:</strong></p>
    <div class="message-box">${message.trim().replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
    
    <div class="footer">
      This email was automatically generated by the RentX Contact Form Handler.
    </div>
  </div>
</body>
</html>
    `.trim();

    // 5. Send via Resend REST API
    console.log("[Route Handler] Calling Resend API to send email...");
    const resendResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${resendApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "RentX Contact <support@rentx.us>",
        to: [contactToEmail],
        reply_to: email.trim(),
        replyTo: email.trim(),
        subject: "New RentX Contact Form Submission",
        text: textContent,
        html: htmlContent,
      }),
    });

    console.log(`[Route Handler] Resend API response status: ${resendResponse.status}`);

    // 6. If Resend API fails, return exact safe error message
    if (!resendResponse.ok) {
      let errorMessage = `Resend API Error: ${resendResponse.statusText}`;
      try {
        const resendJson = await resendResponse.json() as any;
        if (resendJson && resendJson.message) {
          errorMessage = resendJson.message;
        } else if (resendJson && typeof resendJson === "object") {
          errorMessage = JSON.stringify(resendJson);
        }
      } catch {
        const resendText = await resendResponse.text().catch(() => "");
        if (resendText) {
          errorMessage = resendText;
        }
      }
      console.error("[Route Handler] Resend API Error:", errorMessage);
      return NextResponse.json({ success: false, error: errorMessage }, { status: resendResponse.status });
    }

    console.log("[Route Handler] Email sent successfully.");
    return NextResponse.json({ success: true }, { status: 200 });
  } catch (error: any) {
    console.error("[Route Handler] Unexpected error in POST handler:", error);
    return NextResponse.json({ success: false, error: error.message || "An unexpected server error occurred." }, { status: 500 });
  }
}
